function [De] = D_q_e(q)

  De(1,1)=IT + 2*If + 2*It + MT*PT^2 + 2*Mf*Pf^2 + 2*Mt*Pt^2 + MT*lf^2 + MT*lt^2 + 2*Mf*lf^2 + 2*Mf*...
         lt^2 + 2*Mt*lf^2 + 2*Mt*lt^2 - 2*Mf*Pf*lf - 2*Mt*Pt*lt - 2*Mt*lf^2*cos(q(2) - q(3)) - 2*MT*PT*lt*...
         cos(q(2) + q(4)) - 2*MT*PT*lf*cos(q(2)) - 2*Mf*Pf*lt*cos(q(4)) + 2*Mt*Pt*lf*cos(q(5)) + 2*MT*lf*lt*cos(q(4)) +...
          4*Mf*lf*lt*cos(q(4)) + 2*Mt*lf*lt*cos(q(4)) - 2*Mf*Pf*lf*cos(q(2) - q(3)) - 2*Mt*Pt*lt*cos(q(2) -...
          q(3) + q(4) - q(5)) - 2*Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - 2*Mt*Pt*lf*cos(q(3) - q(2) + q(5)) - 2*Mt*lf*...
         lt*cos(q(2) - q(3) + q(4));
  De(1,2)=If + It + Mf*Pf^2 + Mt*Pt^2 + MT*lf^2 + MT*lt^2 + 2*Mf*lf^2 + 2*Mf*lt^2 + Mt*lf^2 + 2*Mt*...
         lt^2 - 2*Mf*Pf*lf - 2*Mt*Pt*lt - Mt*lf^2*cos(q(2) - q(3)) - MT*PT*lt*cos(q(2) + q(4)) - MT*PT*lf*...
         cos(q(2)) - 2*Mf*Pf*lt*cos(q(4)) + 2*MT*lf*lt*cos(q(4)) + 4*Mf*lf*lt*cos(q(4)) + 2*Mt*lf*lt*cos(q(4)) - Mf*Pf*...
         lf*cos(q(2) - q(3)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*...
         Pt*lf*cos(q(3) - q(2) + q(5)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(1,3)=If + It + Mf*Pf^2 + Mt*Pt^2 + Mt*lf^2 - Mt*lf^2*cos(q(2) - q(3)) + 2*Mt*Pt*lf*cos(q(5)) -...
          Mf*Pf*lf*cos(q(2) - q(3)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) +...
          q(4)) - Mt*Pt*lf*cos(q(3) - q(2) + q(5)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(1,4)=It + Mt*Pt^2 + MT*lt^2 + 2*Mf*lt^2 + 2*Mt*lt^2 - 2*Mt*Pt*lt - MT*PT*lt*cos(q(2) + q(4)) -...
          Mf*Pf*lt*cos(q(4)) + MT*lf*lt*cos(q(4)) + 2*Mf*lf*lt*cos(q(4)) + Mt*lf*lt*cos(q(4)) - Mt*Pt*lt*...
         cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(1,5)=It + Mt*Pt^2 + Mt*Pt*lf*cos(q(5)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mt*Pt*lf*...
         cos(q(3) - q(2) + q(5));
  De(1,6)=Mt*Pt*cos(q(1) + q(2) + q(4)) + Mt*Pt*cos(q(1) + q(3) + q(5)) - MT*lt*cos(q(1) + q(2) +...
          q(4)) - 2*Mf*lt*cos(q(1) + q(2) + q(4)) - 2*Mt*lt*cos(q(1) + q(2) + q(4)) + Mf*Pf*cos(q(1) + q(2)) + Mf*Pf*...
         cos(q(1) + q(3)) - MT*lf*cos(q(1) + q(2)) - 2*Mf*lf*cos(q(1) + q(2)) - Mt*lf*cos(q(1) + q(2)) + Mt*lf*...
         cos(q(1) + q(3)) + MT*PT*cos(q(1));
  De(1,7)=MT*lt*sin(q(1) + q(2) + q(4)) - Mt*Pt*sin(q(1) + q(3) + q(5)) - Mt*Pt*sin(q(1) + q(2) +...
          q(4)) + 2*Mf*lt*sin(q(1) + q(2) + q(4)) + 2*Mt*lt*sin(q(1) + q(2) + q(4)) - Mf*Pf*sin(q(1) + q(2)) - Mf*Pf*...
         sin(q(1) + q(3)) + MT*lf*sin(q(1) + q(2)) + 2*Mf*lf*sin(q(1) + q(2)) + Mt*lf*sin(q(1) + q(2)) - Mt*lf*...
         sin(q(1) + q(3)) - MT*PT*sin(q(1));
  De(2,1)=If + It + Mf*Pf^2 + Mt*Pt^2 + MT*lf^2 + MT*lt^2 + 2*Mf*lf^2 + 2*Mf*lt^2 + Mt*lf^2 + 2*Mt*...
         lt^2 - 2*Mf*Pf*lf - 2*Mt*Pt*lt - Mt*lf^2*cos(q(2) - q(3)) - MT*PT*lt*cos(q(2) + q(4)) - MT*PT*lf*...
         cos(q(2)) - 2*Mf*Pf*lt*cos(q(4)) + 2*MT*lf*lt*cos(q(4)) + 4*Mf*lf*lt*cos(q(4)) + 2*Mt*lf*lt*cos(q(4)) - Mf*Pf*...
         lf*cos(q(2) - q(3)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*...
         Pt*lf*cos(q(3) - q(2) + q(5)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(2,2)=If + It + Mf*Pf^2 + Mt*Pt^2 + MT*lf^2 + MT*lt^2 + 2*Mf*lf^2 + 2*Mf*lt^2 + Mt*lf^2 + 2*Mt*...
         lt^2 - 2*Mf*Pf*lf - 2*Mt*Pt*lt - 2*Mf*Pf*lt*cos(q(4)) + 2*MT*lf*lt*cos(q(4)) + 4*Mf*lf*lt*cos(q(4)) + 2*...
         Mt*lf*lt*cos(q(4));
  De(2,3)=- Mt*lf^2*cos(q(2) - q(3)) - Mf*Pf*lf*cos(q(2) - q(3)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) -...
          q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*Pt*lf*cos(q(3) - q(2) + q(5)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(2,4)=It + Mt*Pt^2 + MT*lt^2 + 2*Mf*lt^2 + 2*Mt*lt^2 - 2*Mt*Pt*lt - Mf*Pf*lt*cos(q(4)) + MT*lf*...
         lt*cos(q(4)) + 2*Mf*lf*lt*cos(q(4)) + Mt*lf*lt*cos(q(4));
  De(2,5)=- Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mt*Pt*lf*cos(q(3) - q(2) + q(5));
  De(2,6)=Mt*Pt*cos(q(1) + q(2) + q(4)) - MT*lt*cos(q(1) + q(2) + q(4)) - 2*Mf*lt*cos(q(1) + q(2) +...
          q(4)) - 2*Mt*lt*cos(q(1) + q(2) + q(4)) + Mf*Pf*cos(q(1) + q(2)) - MT*lf*cos(q(1) + q(2)) - 2*Mf*lf*...
         cos(q(1) + q(2)) - Mt*lf*cos(q(1) + q(2));
  De(2,7)=MT*lt*sin(q(1) + q(2) + q(4)) - Mt*Pt*sin(q(1) + q(2) + q(4)) + 2*Mf*lt*sin(q(1) + q(2) +...
          q(4)) + 2*Mt*lt*sin(q(1) + q(2) + q(4)) - Mf*Pf*sin(q(1) + q(2)) + MT*lf*sin(q(1) + q(2)) + 2*Mf*lf*...
         sin(q(1) + q(2)) + Mt*lf*sin(q(1) + q(2));
  De(3,1)=If + It + Mf*Pf^2 + Mt*Pt^2 + Mt*lf^2 - Mt*lf^2*cos(q(2) - q(3)) + 2*Mt*Pt*lf*cos(q(5)) -...
          Mf*Pf*lf*cos(q(2) - q(3)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) +...
          q(4)) - Mt*Pt*lf*cos(q(3) - q(2) + q(5)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(3,2)=- Mt*lf^2*cos(q(2) - q(3)) - Mf*Pf*lf*cos(q(2) - q(3)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) -...
          q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*Pt*lf*cos(q(3) - q(2) + q(5)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(3,3)=If + It + Mf*Pf^2 + Mt*Pt^2 + Mt*lf^2 + 2*Mt*Pt*lf*cos(q(5));
  De(3,4)=- Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*lf*lt*...
         cos(q(2) - q(3) + q(4));
  De(3,5)=It + Mt*Pt^2 + Mt*Pt*lf*cos(q(5));
  De(3,6)=Mt*Pt*cos(q(1) + q(3) + q(5)) + Mf*Pf*cos(q(1) + q(3)) + Mt*lf*cos(q(1) + q(3));
  De(3,7)=- Mt*Pt*sin(q(1) + q(3) + q(5)) - Mf*Pf*sin(q(1) + q(3)) - Mt*lf*sin(q(1) + q(3));
  De(4,1)=It + Mt*Pt^2 + MT*lt^2 + 2*Mf*lt^2 + 2*Mt*lt^2 - 2*Mt*Pt*lt - MT*PT*lt*cos(q(2) + q(4)) -...
          Mf*Pf*lt*cos(q(4)) + MT*lf*lt*cos(q(4)) + 2*Mf*lf*lt*cos(q(4)) + Mt*lf*lt*cos(q(4)) - Mt*Pt*lt*...
         cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*lf*lt*cos(q(2) - q(3) + q(4));
  De(4,2)=It + Mt*Pt^2 + MT*lt^2 + 2*Mf*lt^2 + 2*Mt*lt^2 - 2*Mt*Pt*lt - Mf*Pf*lt*cos(q(4)) + MT*lf*...
         lt*cos(q(4)) + 2*Mf*lf*lt*cos(q(4)) + Mt*lf*lt*cos(q(4));
  De(4,3)=- Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mf*Pf*lt*cos(q(2) - q(3) + q(4)) - Mt*lf*lt*...
         cos(q(2) - q(3) + q(4));
  De(4,4)=It + Mt*Pt^2 + MT*lt^2 + 2*Mf*lt^2 + 2*Mt*lt^2 - 2*Mt*Pt*lt;
  De(4,5)=-Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5));
  De(4,6)=-cos(q(1) + q(2) + q(4))*(MT*lt + 2*Mf*lt + 2*Mt*lt - Mt*Pt);
  De(4,7)=sin(q(1) + q(2) + q(4))*(MT*lt + 2*Mf*lt + 2*Mt*lt - Mt*Pt);
  De(5,1)=It + Mt*Pt^2 + Mt*Pt*lf*cos(q(5)) - Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mt*Pt*lf*...
         cos(q(3) - q(2) + q(5));
  De(5,2)=- Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5)) - Mt*Pt*lf*cos(q(3) - q(2) + q(5));
  De(5,3)=It + Mt*Pt^2 + Mt*Pt*lf*cos(q(5));
  De(5,4)=-Mt*Pt*lt*cos(q(2) - q(3) + q(4) - q(5));
  De(5,5)=It + Mt*Pt^2;
  De(5,6)=Mt*Pt*cos(q(1) + q(3) + q(5));
  De(5,7)=-Mt*Pt*sin(q(1) + q(3) + q(5));
  De(6,1)=Mt*Pt*cos(q(1) + q(2) + q(4)) + Mt*Pt*cos(q(1) + q(3) + q(5)) - MT*lt*cos(q(1) + q(2) +...
          q(4)) - 2*Mf*lt*cos(q(1) + q(2) + q(4)) - 2*Mt*lt*cos(q(1) + q(2) + q(4)) + Mf*Pf*cos(q(1) + q(2)) + Mf*Pf*...
         cos(q(1) + q(3)) - MT*lf*cos(q(1) + q(2)) - 2*Mf*lf*cos(q(1) + q(2)) - Mt*lf*cos(q(1) + q(2)) + Mt*lf*...
         cos(q(1) + q(3)) + MT*PT*cos(q(1));
  De(6,2)=Mt*Pt*cos(q(1) + q(2) + q(4)) - MT*lt*cos(q(1) + q(2) + q(4)) - 2*Mf*lt*cos(q(1) + q(2) +...
          q(4)) - 2*Mt*lt*cos(q(1) + q(2) + q(4)) + Mf*Pf*cos(q(1) + q(2)) - MT*lf*cos(q(1) + q(2)) - 2*Mf*lf*...
         cos(q(1) + q(2)) - Mt*lf*cos(q(1) + q(2));
  De(6,3)=Mt*Pt*cos(q(1) + q(3) + q(5)) + Mf*Pf*cos(q(1) + q(3)) + Mt*lf*cos(q(1) + q(3));
  De(6,4)=-cos(q(1) + q(2) + q(4))*(MT*lt + 2*Mf*lt + 2*Mt*lt - Mt*Pt);
  De(6,5)=Mt*Pt*cos(q(1) + q(3) + q(5));
  De(6,6)=MT + 2*Mf + 2*Mt;
  De(6,7)=0;
  De(7,1)=MT*lt*sin(q(1) + q(2) + q(4)) - Mt*Pt*sin(q(1) + q(3) + q(5)) - Mt*Pt*sin(q(1) + q(2) +...
          q(4)) + 2*Mf*lt*sin(q(1) + q(2) + q(4)) + 2*Mt*lt*sin(q(1) + q(2) + q(4)) - Mf*Pf*sin(q(1) + q(2)) - Mf*Pf*...
         sin(q(1) + q(3)) + MT*lf*sin(q(1) + q(2)) + 2*Mf*lf*sin(q(1) + q(2)) + Mt*lf*sin(q(1) + q(2)) - Mt*lf*...
         sin(q(1) + q(3)) - MT*PT*sin(q(1));
  De(7,2)=MT*lt*sin(q(1) + q(2) + q(4)) - Mt*Pt*sin(q(1) + q(2) + q(4)) + 2*Mf*lt*sin(q(1) + q(2) +...
          q(4)) + 2*Mt*lt*sin(q(1) + q(2) + q(4)) - Mf*Pf*sin(q(1) + q(2)) + MT*lf*sin(q(1) + q(2)) + 2*Mf*lf*...
         sin(q(1) + q(2)) + Mt*lf*sin(q(1) + q(2));
  De(7,3)=- Mt*Pt*sin(q(1) + q(3) + q(5)) - Mf*Pf*sin(q(1) + q(3)) - Mt*lf*sin(q(1) + q(3));
  De(7,4)=sin(q(1) + q(2) + q(4))*(MT*lt + 2*Mf*lt + 2*Mt*lt - Mt*Pt);
  De(7,5)=-Mt*Pt*sin(q(1) + q(3) + q(5));
  De(7,6)=0;
  De(7,7)=MT + 2*Mf + 2*Mt;

 